{% set name = "eth-keyfile" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02e3c2e564c7403b92db3fef8ecae3d21123b15787daecd5b643a57369c530f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-markdown
  run:
    - eth-utils >=2.0.0
    - eth-keys >=0.4.0
    - pycryptodome >=3.6.6,<4.0.0
    - python >=3.6

test:
  imports:
    - eth_keyfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-keyfile
  summary: A library for handling the encrypted keyfiles used to store ethereum private keys.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
