{% set name = "eth-keyfile" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9708bc31f386b52cca0969238ff35b1ac72bd7a7186f2a84b86110d3c973bec1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - setuptools-markdown
  run:
    - eth-utils >=2.0.0
    - eth-keys >=0.4.0
    - pycryptodome >=3.6.6,<4.0.0
    - python >={{ python_min }}

test:
  imports:
    - eth_keyfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/eth-keyfile
  summary: A library for handling the encrypted keyfiles used to store ethereum private keys.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
