{% set name = "eth-keyfile" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d30597cdecb8ccd3b56bb275cd86fcdc7a279f86eafa92ddc49f66512f0bff67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-markdown
  run:
    - cytoolz >=0.9.0,<1.0.0
    - eth-keys >=0.4.0,<0.5.0
    - eth-utils >=2.0.0,<3.0.0
    - pycryptodome >=3.4.7,<4.0.0
    - python >=3.6

test:
  imports:
    - eth_keyfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-keyfile
  summary: A library for handling the encrypted keyfiles used to store ethereum private keys.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
